#!/bin/bash
set -e

# Gemini Phone Bot Installer (LXC Mode)
# Usage: curl -sSL https://raw.githubusercontent.com/jayis1/claude-phone-but-for-Gemini-and-freepbx/main/install-bot.sh | bash -s -- --ext 9000 --name Morpheus --registrar 172.16.1.26
# Arguments:
#   --ext 9000
#   --name Morpheus
#   --pass changeme
#   --registrar 172.16.1.26 (FreePBX IP)
#   --external-ip 192.168.1.105 (Optional Manual IP)

REPO_URL="https://github.com/jayis1/claude-phone-but-for-Gemini-and-freepbx.git"
INSTALL_DIR="$HOME/gemini-bot"

# --- Parse Arguments ---
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --ext) EXTENSION="$2"; shift ;;
        --name) INSTANCE_NAME="$2"; shift ;;
        --pass) PASSWORD="$2"; shift ;;
        --registrar) REGISTRAR="$2"; shift ;;
        --external-ip) EXTERNAL_IP="$2"; shift ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

PASSWORD=${PASSWORD:-"changeme"}

if [ -z "$EXTENSION" ] || [ -z "$REGISTRAR" ]; then
    echo "Usage: curl ... | bash -s -- --ext 9000 --registrar 172.16.1.26 [--name Name] [--pass Password]"
    exit 1
fi

echo "🤖 Deploying Bot: $INSTANCE_NAME ($EXTENSION)..."

# --- 1. System Dependencies (Docker/Git) ---
if ! command -v git &> /dev/null; then
    echo "📦 Installing Git..."
    sudo apt-get update && sudo apt-get install -y git curl
fi

if ! command -v docker &> /dev/null; then
    echo "📦 Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker $USER
    # Note: User might need to re-login if running interactively.
    # We will use 'sg docker' or assume root/privileged.
fi

# --- 2. Clone Repository ---
if [ -d "$INSTALL_DIR" ]; then
    echo "♻️ Updating existing repo..."
    cd "$INSTALL_DIR"
    git pull
else
    echo "📥 Cloning repository..."
    git clone "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# --- 3. Configure Environment ---
cd voice-app

# Auto-detect IP if not provided
if [ -z "$EXTERNAL_IP" ]; then
    EXTERNAL_IP=$(hostname -I | awk '{print $1}')
fi
echo "🌐 Detected IP: $EXTERNAL_IP"

echo "📝 Writing .env config..."
cat > .env <<EOF
# Generated by install-bot.sh
HTTP_PORT=3000
WS_PORT=3001
SIP_EXTENSION=$EXTENSION
SIP_AUTH_ID=$EXTENSION
SIP_PASSWORD=$PASSWORD
SIP_DOMAIN=$REGISTRAR
SIP_REGISTRAR=$REGISTRAR
SIP_REGISTRAR_PORT=5060
INSTANCE_NAME="$INSTANCE_NAME"
EXTERNAL_IP=$EXTERNAL_IP

# Container Configs
DRACHTIO_HOST=drachtio
DRACHTIO_PORT=9022
DRACHTIO_SECRET=cymru
FREESWITCH_HOST=freeswitch
FREESWITCH_PORT=8021
FREESWITCH_SECRET=JambonzR0ck$
AUDIO_DIR=/tmp/voice-audio
EOF

# --- 4. Launch Container ---
echo "🚀 Launching Bot Container..."
# Try to use 'docker compose' (v2) or 'docker-compose' (v1)
if docker compose version &> /dev/null; then
    CMD="docker compose"
elif command -v docker-compose &> /dev/null; then
    CMD="docker-compose"
else
    echo "❌ Docker Compose not found. Installing plugin..."
    sudo apt-get install -y docker-compose-plugin
    CMD="docker compose"
fi

# Run up -d
$CMD up -d --build

echo ""
echo "✅ Bot Deployment Complete!"
echo "   Name: $INSTANCE_NAME"
echo "   Ext:  $EXTENSION"
echo "   Host: $EXTERNAL_IP"
echo "   Registrar: $REGISTRAR"
echo ""
