#!/bin/bash

# Whitelist LXC IP in FreePBX Fail2ban
# Run this on the FreePBX server to whitelist crew member IPs

set -e

FAIL2BAN_WHITELIST="/etc/fail2ban/jail.local"
BACKUP_FILE="/etc/fail2ban/jail.local.backup-$(date +%Y%m%d-%H%M%S)"

echo "🔒 FreePBX Fail2ban Whitelist Manager"
echo ""

# Check if running on FreePBX server
if [ ! -f "/etc/freepbx.conf" ]; then
    echo "✗ This script must run on the FreePBX server"
    exit 1
fi

# Check if fail2ban is installed
if ! command -v fail2ban-client &> /dev/null; then
    echo "✗ fail2ban is not installed"
    exit 1
fi

# Get IP to whitelist
if [ -z "$1" ]; then
    echo "Usage: $0 <IP_ADDRESS> [DESCRIPTION]"
    echo ""
    echo "Example:"
    echo "  $0 172.16.1.100 'Morpheus LXC'"
    echo "  $0 172.16.1.0/24 'Entire LXC subnet'"
    exit 1
fi

IP_TO_WHITELIST="$1"
DESCRIPTION="${2:-AI Phone Crew Member}"

# Validate IP format (basic check)
if ! echo "$IP_TO_WHITELIST" | grep -qE '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(/[0-9]{1,2})?$'; then
    echo "✗ Invalid IP address format: $IP_TO_WHITELIST"
    exit 1
fi

# Backup existing config
if [ -f "$FAIL2BAN_WHITELIST" ]; then
    echo "→ Backing up existing config to $BACKUP_FILE"
    cp "$FAIL2BAN_WHITELIST" "$BACKUP_FILE"
fi

# Check if IP already whitelisted
if [ -f "$FAIL2BAN_WHITELIST" ] && grep -q "$IP_TO_WHITELIST" "$FAIL2BAN_WHITELIST"; then
    echo "✓ IP $IP_TO_WHITELIST is already whitelisted"
    exit 0
fi

# Create or update jail.local
if [ ! -f "$FAIL2BAN_WHITELIST" ]; then
    echo "→ Creating new jail.local"
    cat > "$FAIL2BAN_WHITELIST" << EOF
# FreePBX Fail2ban Configuration
# Auto-generated by AI Phone

[DEFAULT]
# Whitelisted IPs (never ban these)
ignoreip = 127.0.0.1/8 ::1
           $IP_TO_WHITELIST  # $DESCRIPTION

[asterisk]
enabled = true
EOF
else
    # Add IP to existing ignoreip line
    echo "→ Adding $IP_TO_WHITELIST to whitelist"
    
    # Check if [DEFAULT] section exists
    if grep -q "^\[DEFAULT\]" "$FAIL2BAN_WHITELIST"; then
        # Add to existing ignoreip or create it
        if grep -q "^ignoreip" "$FAIL2BAN_WHITELIST"; then
            # Append to existing ignoreip
            sed -i "/^ignoreip/a\           $IP_TO_WHITELIST  # $DESCRIPTION" "$FAIL2BAN_WHITELIST"
        else
            # Add ignoreip line after [DEFAULT]
            sed -i "/^\[DEFAULT\]/a ignoreip = 127.0.0.1/8 ::1\n           $IP_TO_WHITELIST  # $DESCRIPTION" "$FAIL2BAN_WHITELIST"
        fi
    else
        # Add [DEFAULT] section at the top
        sed -i "1i [DEFAULT]\nignoreip = 127.0.0.1/8 ::1\n           $IP_TO_WHITELIST  # $DESCRIPTION\n" "$FAIL2BAN_WHITELIST"
    fi
fi

# Restart fail2ban
echo "→ Restarting fail2ban..."
systemctl restart fail2ban

# Verify
echo ""
echo "✓ Successfully whitelisted $IP_TO_WHITELIST"
echo ""
echo "Current whitelisted IPs:"
grep -A 10 "^ignoreip" "$FAIL2BAN_WHITELIST" || echo "  (none configured)"
echo ""
echo "Fail2ban status:"
fail2ban-client status

echo ""
echo "✅ Done! $IP_TO_WHITELIST will never be banned by fail2ban"
